import { createSlice } from '@reduxjs/toolkit';
import { ThemeState } from '../types';

/**
 * Initial state for the theme slice.
 */
const initialState: ThemeState = {
  darkMode: false,
};

/**
 * Slice for managing theme state.
 */
const themeSlice = createSlice({
  name: 'theme',
  initialState,
  reducers: {
    /**
     * Toggles the dark mode state.
     *
     * @param {ThemeState} state - The current state of the theme.
     */
    toggleTheme(state: ThemeState) {
      state.darkMode = !state.darkMode;
    },
  },
});

// Export the action creators generated by createSlice
export const { toggleTheme } = themeSlice.actions;

// Export the reducer to be used in the store configuration
export default themeSlice.reducer;